// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3PzmTuM_kIOHAHAubFT2tmgRQkwb3WeM',
    appId: '1:674809708770:android:14399d68759d228257debb',
    messagingSenderId: '674809708770',
    projectId: 'dortor-appointment',
    databaseURL: 'https://dortor-appointment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dortor-appointment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1XqlksfW3hc2AINIvr6FmSkgxBfNCe3o',
    appId: '1:674809708770:ios:35925c14ba147cec57debb',
    messagingSenderId: '674809708770',
    projectId: 'dortor-appointment',
    databaseURL: 'https://dortor-appointment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dortor-appointment.appspot.com',
    iosBundleId: 'com.example.doctorAppointment',
  );
}
